// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrshsbzNDWoGmFZpf-dt-NCJQVS95Bq38',
    appId: '1:432625906594:web:32b79a323ceac051a738fb',
    messagingSenderId: '432625906594',
    projectId: 'whatsapp-messenegr-fca52',
    authDomain: 'whatsapp-messenegr-fca52.firebaseapp.com',
    storageBucket: 'whatsapp-messenegr-fca52.firebasestorage.app',
    measurementId: 'G-1PRT1WQJEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYcuQda8AexCyEqnrel3yNstRmDWfW7tU',
    appId: '1:432625906594:android:3f6d74e049a43591a738fb',
    messagingSenderId: '432625906594',
    projectId: 'whatsapp-messenegr-fca52',
    storageBucket: 'whatsapp-messenegr-fca52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdhfyMXmSZo7u798Q2pqXyIg3jrjJ8FiQ',
    appId: '1:432625906594:ios:e435299ac7d5e00ca738fb',
    messagingSenderId: '432625906594',
    projectId: 'whatsapp-messenegr-fca52',
    storageBucket: 'whatsapp-messenegr-fca52.firebasestorage.app',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdhfyMXmSZo7u798Q2pqXyIg3jrjJ8FiQ',
    appId: '1:432625906594:ios:e435299ac7d5e00ca738fb',
    messagingSenderId: '432625906594',
    projectId: 'whatsapp-messenegr-fca52',
    storageBucket: 'whatsapp-messenegr-fca52.firebasestorage.app',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrshsbzNDWoGmFZpf-dt-NCJQVS95Bq38',
    appId: '1:432625906594:web:bcf7af5a84e97c2aa738fb',
    messagingSenderId: '432625906594',
    projectId: 'whatsapp-messenegr-fca52',
    authDomain: 'whatsapp-messenegr-fca52.firebaseapp.com',
    storageBucket: 'whatsapp-messenegr-fca52.firebasestorage.app',
    measurementId: 'G-4BJFP8YJ81',
  );
}
